<a href="https://colab.research.google.com/github/Rapolu-Sri-Sanchali/NASSCOM/blob/main/Numpy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

print("--- Intermediate NumPy Exercise ---")
print("Complete each task by writing the requested NumPy code.")
print("-----------------------------------")

# Task 1: Array Creation Shortcuts
print("\n--- Task 1: Array Creation Shortcuts ---")

# 1.1 Create a 1D array named 'arr1_1' with numbers from 0 to 99 (inclusive) using arange.
arr1_1 = np.arange(100)

# 1.2 Create a 3x3 array named 'arr1_2' filled with ones.
arr1_2 = np.ones((3, 3))

# 1.3 Create a 2x4 array named 'arr1_3' filled with the number 7.
arr1_3 = np.full((2, 4), 7)

# 1.4 Create a 5x5 array named 'arr1_4' with random integers between 10 and 50 (inclusive).
arr1_4 = np.random.randint(10, 51, size=(5, 5))

print("arr1_1 (first 10 elements):", arr1_1[:10])
print("arr1_2:\n", arr1_2)
print("arr1_3:\n", arr1_3)
print("arr1_4 (first 2 rows):\n", arr1_4[:2])


# Task 2: Indexing and Slicing with Arrays
print("\n--- Task 2: Indexing and Slicing with Arrays ---")

data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])

# 2.1
val2_1 = data[2, 3]

# 2.2
row2_2 = data[0]

# 2.3
col2_3 = data[:, -1]

# 2.4
sub_arr2_4 = data[1:3, 0:2]

# 2.5
filtered_elements2_5 = data[data > 100]

print("Value:", val2_1)
print("First row:", row2_2)
print("Last column:", col2_3)
print("Sub-array:\n", sub_arr2_4)
print("Elements > 100:", filtered_elements2_5)


# Task 3: Conditional Operations
print("\n--- Task 3: Conditional Operations ---")

arr3_1 = np.random.randint(1, 21, size=(4, 5))

# 3.1
arr3_2 = np.where(arr3_1 < 10, 0, arr3_1)

# 3.2
even_count3_3 = np.sum(arr3_1 % 2 == 0)

print("Original array:\n", arr3_1)
print("Modified array:\n", arr3_2)
print("Even count:", even_count3_3)


# Task 4: Aggregation Functions
print("\n--- Task 4: Aggregation Functions ---")

arr4_1 = np.array([[10, 5, 12],
                   [3, 8, 15],
                   [20, 7, 4]])

# 4.1
sum4_1 = np.sum(arr4_1)

# 4.2
mean_cols4_2 = np.mean(arr4_1, axis=0)

# 4.3
max_rows4_3 = np.max(arr4_1, axis=1)

# 4.4
std4_4 = np.std(arr4_1)

print("Sum:", sum4_1)
print("Column means:", mean_cols4_2)
print("Row maximums:", max_rows4_3)
print("Standard deviation:", std4_4)


# Task 5: Reshaping and Flattening
print("\n--- Task 5: Reshaping and Flattening ---")

arr5_1 = np.arange(24)

# 5.1
reshaped_arr5_2 = arr5_1.reshape(4, 6)

# 5.2
reshaped_arr5_3 = arr5_1.reshape(2, 3, 4)

# 5.3
flattened_arr5_4 = reshaped_arr5_2.ravel()
flattened_arr5_4_copy = reshaped_arr5_2.flatten()

print("4x6 Array:\n", reshaped_arr5_2)
print("2x3x4 Array:\n", reshaped_arr5_3)
print("Flattened (ravel):", flattened_arr5_4)
print("Flattened (flatten):", flattened_arr5_4_copy)


# Task 6: Broadcasting
print("\n--- Task 6: Broadcasting ---")

arr6_1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

scalar = 10
vector = np.array([100, 200, 300])

# 6.1
result6_1 = arr6_1 + scalar

# 6.2
result6_2 = arr6_1 + vector

print("Scalar addition:\n", result6_1)
print("Vector addition:\n", result6_2)


# Task 7: Copying vs. Viewing Arrays
print("\n--- Task 7: Copying vs. Viewing Arrays ---")

original_arr7 = np.array([1, 2, 3, 4, 5])

# 7.1
view_arr7 = original_arr7[:]
view_arr7[0] = 99

# 7.2
copy_arr7 = original_arr7.copy()
copy_arr7[-1] = 0

print("Original array:", original_arr7)
print("View array:", view_arr7)
print("Copy array:", copy_arr7)


# Task 8: Stacking and Splitting Arrays
print("\n--- Task 8: Stacking and Splitting Arrays ---")

arr8_a = np.array([[1, 2], [3, 4]])
arr8_b = np.array([[5, 6], [7, 8]])
arr8_c = np.array([[9, 10]])

# 8.1
vstack_arr8_1 = np.vstack((arr8_a, arr8_b))

# 8.2
hstack_arr8_2 = np.hstack((arr8_a, arr8_b))

# 8.3
combined_arr8_3 = np.vstack((vstack_arr8_1, arr8_c))

# 8.4
part1, part2, part3 = np.vsplit(combined_arr8_3, [2, 4])

print("Vertical Stack:\n", vstack_arr8_1)
print("Horizontal Stack:\n", hstack_arr8_2)
print("Combined Array:\n", combined_arr8_3)
print("Part 1:\n", part1)
print("Part 2:\n", part2)
print("Part 3:\n", part3)


# Task 9: Sorting and Searching
print("\n--- Task 9: Sorting and Searching ---")

arr9_1 = np.array([5, 2, 8, 1, 9, 4, 7, 3, 6])

arr9_2d = np.array([[30, 20, 10],
                    [60, 50, 40],
                    [90, 80, 70]])

# 9.1
sorted_arr9_1 = np.sort(arr9_1)

# 9.2
sorted_cols9_2 = np.sort(arr9_2d, axis=0)

# 9.3
idx9_3 = np.where(arr9_1 == 9)

# 9.4
max_idx9_4 = np.argmax(arr9_1)

print("Sorted 1D array:", sorted_arr9_1)
print("Column-wise sorted 2D array:\n", sorted_cols9_2)
print("Index of 9:", idx9_3)
print("Index of maximum value:", max_idx9_4)

--- Intermediate NumPy Exercise ---
Complete each task by writing the requested NumPy code.
-----------------------------------

--- Task 1: Array Creation Shortcuts ---
arr1_1 (first 10 elements): [0 1 2 3 4 5 6 7 8 9]
arr1_2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arr1_3:
 [[7 7 7 7]
 [7 7 7 7]]
arr1_4 (first 2 rows):
 [[20 26 43 13 26]
 [22 36 11 48 25]]

--- Task 2: Indexing and Slicing with Arrays ---
Value: 120
First row: [10 20 30 40]
Last column: [ 40  80 120 160]
Sub-array:
 [[ 50  60]
 [ 90 100]]
Elements > 100: [110 120 130 140 150 160]

--- Task 3: Conditional Operations ---
Original array:
 [[17 20 14  5 19]
 [18  7 15 19 19]
 [16  8 16  2 17]
 [ 1  4 10 17 17]]
Modified array:
 [[17 20 14  0 19]
 [18  0 15 19 19]
 [16  0 16  0 17]
 [ 0  0 10 17 17]]
Even count: 9

--- Task 4: Aggregation Functions ---
Sum: 84
Column means: [11.          6.66666667 10.33333333]
Row maximums: [12 15 20]
Standard deviation: 5.2493385826745405

--- Task 5: Reshaping and Flattening ---
4x6 Arra